# Generated by Django 3.1.13 on 2021-07-27 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lost_in_ready_to_test',
            field=models.DurationField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='lost_in_stop',
            field=models.DurationField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='lost_in_to_reveiw',
            field=models.DurationField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='unused_time',
            field=models.DurationField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
