# Generated by Django 3.1.13 on 2021-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_durattion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
