# Generated by Django 3.1.13 on 2021-08-12 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210808_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Developer', 'Developer'), ('Validator', 'Validator')], max_length=255, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('employees', models.ManyToManyField(to='main.EmployeeModel', verbose_name='Employees')),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Stoped', 'Stoped'), ('Closed', 'Closed')], default='In Progress', max_length=50)),
                ('color', models.CharField(max_length=16, verbose_name='Color')),
                ('members', models.ManyToManyField(to='main.PersonModel', verbose_name='Members')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='entreprisemodel',
            name='projects',
            field=models.ManyToManyField(to='main.ProjectModel', verbose_name='Projects'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personmodel'),
        ),
    ]
